module.exports.affirmations = [
    "Hi!",
    "Hello beautiful person!",
    "You are an amazing human being!",
    "Today has countless possibilities.",
    "You are a gift to this world.",
    "It takes a lot of courage to be who you are.",
    "Remember that your current situation is not your final destination.",
    "You are amazing just the way you are.",
    "Shoot for the stars, even if you miss you are still among the stars.",
    "Don’t be afraid of slow progress, baby steps still move you forward.",
    "Nothing is perfect, that’s why erasers exist.",
    "Winning doesn’t mean being first. It means you’re doing better than you’ve done before.",
    "If an opportunity doesn’t knock, build a door.",
    "Our world is better because you are in it",
    "I know it’s tough right now but it won’t last forever",
    "Your story matters",
    "We got you!",
    "I think you’re pretty great!",
    "Trust the timing of your life	",
    "It’s ok to not be ok",
    "You are capable",
    "You are frickin’ awesome!",
    "When nothing goes right, go left",
    "Broken crayons still color",
    "If it matters to you, you will find a way.",
    "Dream without fear. Love without limits.",
    "You are loved.",
    "Focus on the journey, not the destination.",
    "Enjoy the little things in life.",
    "Throw kindness like confetti.",
    "By the way, I’m wearing the smile you gave me.",
    "When there is rain look for rainbows. When it’s dark look for stars.",
    "Be kind to unkind people. They need it the most.",
    "Treat yourself the way that you treat others.",
    "Be kind to yourself.",
    "Don’t count the days make the days count",
    "Love the life you live. Lead the life you love",
    "Life is accepting what is and making it work for you",
    "Storms don’t last forever",
    "I will sit with you in the dark",
    "Whatever is good for your soul, do that",
    "Love your mind",
    "Speak your truth",
    "Normal is boring",
    "Don’t let the world change your smile",
    "You are enough",
    "Why fit in when you were born to stand out?",
    "Accept who you are. Unless you are a serial killer.",
    "Be yourself. People don’t have to like you, and you don’t have to care.",
    "Your worth isn’t determined by others opinions.",
    "It’s ok to put yourself first",
    "There is no competition because nobody is better at being you than you",
    "If you can dream it, you can do it",
    "Inhale the future and exhale the past",
];
